version: "3.2"

services:
  elasticsearch:
    image: elasticsearch:7.4.1             //镱像(image)
    restart: always                        //重启方式
    environment:
      discovery.type: single-node          //环境变量：运行模式 单例
    ports:
      - "9200:9200"                        //端口映射
      - "9300:9300"
  kibana:
    image: kibana:7.4.1                     //镱像(image)
    restart: always                         //重启方式
    environment:
      ELASTICSEARCH_URL: "127.0.0.1:9200"   //环境变量：elasticsearch 请求地址
      I18N_LOCALE: "zh-CN"                  //指定中文
    ports:
      - "5601:5601"                        //端口映射


# 在使用之前需要首先拉取仓库的镜像
# docker pull elasticsearch:7.4.1
# docker pull kibana:7.4.1

